LivrariaHBSIS/LivrariaHBSIS.Web/Controllers/GeneroController.cs
using LivrariaHBSIS.domain.Interfaces.Services;
using LivrariaHBSIS.Web.ViewModel;
using System;
using System.Linq;
using System.Web.Mvc;

namespace LivrariaHBSIS.Web.Controllers
{
    public class GeneroController : Controller
    {
        private readonly IGeneroService _generoService;

        public GeneroController(IGeneroService generoService)
        {
            _generoService = generoService;
        }

        public ActionResult Index()
        {
            var generosViewModel = _generoService
                .ListarGeneros()
                .Select(g => new GeneroViewModel
                {
                    Id = g.Id,
                    Descricao = g.Descricao
                }).ToList();
            return View(generosViewModel);
        }

        public ActionResult Create()
        {
            return View(new GeneroViewModel());
        }

        [HttpPost]
        public ActionResult Create(GeneroViewModel generoViewModel)
        {
            try
            {
                _generoService.IncluirGenero(generoViewModel.GeneroViewModelToGenero());
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var genero = _generoService.RecuperarGeneroPorId(id);
            return View(new GeneroViewModel(genero.Id, genero.Descricao));
        }

        [HttpPost]
        public ActionResult Edit(int id, GeneroViewModel generoViewModel)
        {
            try
            {
                _generoService.EditarGenero(generoViewModel.GeneroViewModelToGenero());
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(long id)
        {
            var genero = _generoService.RecuperarGeneroPorId(id);
            return View(new GeneroViewModel { Id = genero.Id, Descricao = genero.Descricao });
        }

        [HttpPost]
        public ActionResult Delete(int id, GeneroViewModel generoViewModel)
        {
            try
            {
                _generoService.RemoverGenero(generoViewModel.GeneroViewModelToGenero());
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Genero/Create.cshtml
@model LivrariaHBSIS.Web.ViewModel.GeneroViewModel

@{
    ViewBag.Title = "Inclusão";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title">Incluir Gênero</span>
                <div class="row">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="row">
                            <div class="input-field col s12">
                                @Html.LabelFor(model => model.Descricao)
                                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "validate" } })
                                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s12 right-align">
                                @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn red" })
                                <input type="submit" value="Salvar" class="btn btn-default" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Genero/Delete.cshtml
@model LivrariaHBSIS.Web.ViewModel.GeneroViewModel

@{
    ViewBag.Title = "Exclusão";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title"> @Html.DisplayFor(model => model.Descricao)</span>
                <div class="row">
                    <h4>Deseja realmente excluir o Gênero @Html.DisplayFor(model => model.Descricao)?</h4>
                </div>
                <div class="row">
                    <div class="col s12 m12 right-align">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn red" })
                                <input type="submit" value="Excluir" class="btn btn-default green" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Genero/Edit.cshtml
@model LivrariaHBSIS.Web.ViewModel.GeneroViewModel

@{
    ViewBag.Title = "Edição";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title">Editar Gênero</span>
                <div class="row">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="row">
                            <div class="input-field col s12">
                                @Html.LabelFor(model => model.Descricao)
                                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "validate" } })
                                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s12 right-align">
                                @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn red" })
                                <input type="submit" value="Salvar" class="btn btn-default" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Genero/Index.cshtml
@model IEnumerable<LivrariaHBSIS.Web.ViewModel.GeneroViewModel>

@{
    ViewBag.Title = "Gêneros";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title">Gêneros</span>
                <div class="row">
                    <div class="col s12 m12 right-align">
                        @Html.ActionLink("Incluir Gênero", "Create", "Genero", new object { }, new { @class = "btn" })
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 m12">
                        <table class="striped">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Descricao)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Descricao)
                                        </td>
                                        <td>
                                            <a class="btn-floating light-green" href="@Url.Action("Edit", "Genero", new { id = item.Id })"><i class="material-icons">mode_edit</i></a>
                                            <a class="btn-floating red" href="@Url.Action("Delete", "Genero", new { id = item.Id })"><i class="material-icons">delete</i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>