LivrariaHBSIS/LivrariaHBSIS.Web/Controllers/LivroController.cs
using LivrariaHBSIS.domain;
using LivrariaHBSIS.domain.Interfaces.Services;
using LivrariaHBSIS.Web.ViewModel;
using System.Linq;
using System.Web.Mvc;

namespace LivrariaHBSIS.Web.Controllers
{
    public class LivroController : Controller
    {
        private readonly ILivroService _livroService;
        private readonly IAutorService _autorService;
        private readonly IGeneroService _generoService;
        private readonly IEditoraService _editoraService;
        public LivroController(ILivroService livroService, IAutorService autorService, IGeneroService generoService, IEditoraService editoraService)
        {
            _livroService = livroService;
            _autorService = autorService;
            _generoService = generoService;
            _editoraService = editoraService;
        }
        public ActionResult Index()
        {
            var livrosViewModel = _livroService.ListarLivros().Select(livro => new LivroViewModel
            {
                Id = livro.Id,
                AnoPublicacao = livro.AnoPublicacao,
                AutorPrincipal = livro.AutorPrincipal,
                Descricao = livro.Descricao,
                EditoraPublicacao = livro.EditoraPublicacao,
                GeneroLivro = livro.GeneroLivro,
                Isbn = livro.Isbn,
                Titulo = livro.Titulo
            }).OrderBy(l => l.Titulo).ToList();

            return View(livrosViewModel);
        }

        public ActionResult Details(int id)
        {
            var livro = _livroService.RecuperarLivroPorId(id);
            var livroViewModel = new LivroViewModel
            {
                Id = livro.Id,
                AnoPublicacao = livro.AnoPublicacao,
                AutorPrincipal = livro.AutorPrincipal,
                Descricao = livro.Descricao,
                EditoraPublicacao = livro.EditoraPublicacao,
                GeneroLivro = livro.GeneroLivro,
                Isbn = livro.Isbn,
                Titulo = livro.Titulo,
                AutorSelecionado = livro.AutorPrincipal == null ? 0 : livro.AutorPrincipal.Id,
                GeneroSelecionado = livro.GeneroLivro == null ? 0 : livro.GeneroLivro.Id,
                EditoraSelecionada = livro.EditoraPublicacao == null ? 0 : livro.EditoraPublicacao.Id
            };
            return View(livroViewModel);
        }

        public ActionResult Create()
        {
            CarregarItensParaSelect();
            return View();
        }

        [HttpPost]
        public ActionResult Create(LivroViewModel livroViewModel)
        {
            try
            {
                var livro = new Livro
                {
                    AnoPublicacao = livroViewModel.AnoPublicacao,
                    Descricao = livroViewModel.Descricao,
                    EditoraPublicacao = _editoraService.RecuperarEditoraPorId(livroViewModel.EditoraSelecionada),
                    GeneroLivro = _generoService.RecuperarGeneroPorId(livroViewModel.GeneroSelecionado),
                    AutorPrincipal = _autorService.RecuperarAutorPorId(livroViewModel.AutorSelecionado),
                    Isbn = livroViewModel.Isbn,
                    Id = livroViewModel.Id,
                    Titulo = livroViewModel.Titulo
                };
                _livroService.IncluirLivro(livro);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(long id)
        {
            var livro = _livroService.RecuperarLivroPorId(id);
            var livroViewModel = new LivroViewModel
            {
                Id = livro.Id,
                AnoPublicacao = livro.AnoPublicacao,
                AutorPrincipal = livro.AutorPrincipal,
                Descricao = livro.Descricao,
                EditoraPublicacao = livro.EditoraPublicacao,
                GeneroLivro = livro.GeneroLivro,
                Isbn = livro.Isbn,
                Titulo = livro.Titulo,
                AutorSelecionado = livro.AutorPrincipal == null ? 0 : livro.AutorPrincipal.Id,
                GeneroSelecionado = livro.GeneroLivro == null ? 0 : livro.GeneroLivro.Id,
                EditoraSelecionada = livro.EditoraPublicacao == null ? 0 : livro.EditoraPublicacao.Id
            };
            CarregarItensParaSelect();
            return View(livroViewModel);
        }

        [HttpPost]
        public ActionResult Edit(int id, LivroViewModel livroViewModel)
        {
            try
            {
                var livro = new Livro
                {
                    AnoPublicacao = livroViewModel.AnoPublicacao,
                    Descricao = livroViewModel.Descricao,
                    EditoraPublicacao = _editoraService.RecuperarEditoraPorId(livroViewModel.EditoraSelecionada),
                    GeneroLivro = _generoService.RecuperarGeneroPorId(livroViewModel.GeneroSelecionado),
                    AutorPrincipal = _autorService.RecuperarAutorPorId(livroViewModel.AutorSelecionado),
                    Isbn = livroViewModel.Isbn,
                    Id = livroViewModel.Id,
                    Titulo = livroViewModel.Titulo
                };
                _livroService.EditarLivro(livro);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(long id)
        {
            var livro = _livroService.RecuperarLivroPorId(id);
            var livroViewModel = new LivroViewModel
            {
                Id = livro.Id,
                AnoPublicacao = livro.AnoPublicacao,
                AutorPrincipal = livro.AutorPrincipal,
                Descricao = livro.Descricao,
                EditoraPublicacao = livro.EditoraPublicacao,
                GeneroLivro = livro.GeneroLivro,
                Isbn = livro.Isbn,
                Titulo = livro.Titulo
            };
            return View(livroViewModel);
        }

        [HttpPost]
        public ActionResult Delete(int id, LivroViewModel livroViewModel)
        {
            try
            {
                _livroService.RemoverLivro(livroViewModel.LivroViewModelToLivro());
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        private void CarregarItensParaSelect()
        {
            var autores = _autorService
               .ListarAutores()
               .Select(autor => new SelectListItem { Value = autor.Id.ToString(), Text = autor.Nome })
               .ToList();
            ViewBag.SelectListAutores = new SelectList(autores, "Value", "Text");

            var generos = _generoService.ListarGeneros().Select(genero => new SelectListItem { Value = genero.Id.ToString(), Text = genero.Descricao }).ToList();
            ViewBag.SelectListGeneros = new SelectList(generos, "Value", "Text");

            var editoras = _editoraService.ListarEditoras().Select(editora => new SelectListItem { Value = editora.Id.ToString(), Text = editora.Nome }).ToList();
            ViewBag.SelectListEditoras = new SelectList(editoras, "Value", "Text");

        }
    }
}

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Livro/Create.cshtml
@model LivrariaHBSIS.Web.ViewModel.LivroViewModel

@{
    ViewBag.Title = "Catalogar";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title">Catalogar Livro</span>
                <div class="row">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row">
                            <div class="input-field col s12">
                                @Html.LabelFor(model => model.Titulo)
                                @Html.EditorFor(model => model.Titulo, new { @class = "validate", @id = "titulo" } )
                                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                @Html.LabelFor(model => model.Descricao)
                                @Html.TextAreaFor(model => model.Descricao, new { @class = "materialize-textarea validade" , @id = "descricao", data_length = "400" } )
                                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6">
                                @Html.LabelFor(model => model.AnoPublicacao)
                                @Html.TextBoxFor(model => model.AnoPublicacao, new { @type = "number", @min = "1452",  @id = "anoPublicacao"  })
                                @Html.ValidationMessageFor(model => model.AnoPublicacao, "", new { @class = "text-danger" })
                            </div>
                            <div class="input-field col s6">
                                @Html.LabelFor(model => model.Isbn)
                                @Html.TextBoxFor(model => model.Isbn, new { @type = "number",  @id = "isbn"  })
                                @Html.ValidationMessageFor(model => model.Isbn, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6 m6">
                                @Html.DropDownListFor(model => model.AutorSelecionado, (SelectList)ViewBag.SelectListAutores)
                                @Html.LabelFor(model => model.AutorSelecionado)
                            </div>
                            <div class="input-field col s6 m6">
                                @Html.DropDownListFor(model => model.GeneroSelecionado, (SelectList)ViewBag.SelectListGeneros)
                                @Html.LabelFor(model => model.GeneroSelecionado)
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6 m6">
                                @Html.DropDownListFor(model => model.EditoraSelecionada, (SelectList)ViewBag.SelectListEditoras)
                                @Html.LabelFor(model => model.EditoraSelecionada)
                            </div>
                        </div>

                        <div class="row">
                            <div class="col s12 right-align">
                                @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn red" })
                                <input type="submit" value="Salvar" class="btn btn-default" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(document).ready(function () {
        $('input#input_text, textarea#descricao').characterCounter();
    });
</script>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Livro/Delete.cshtml
@model LivrariaHBSIS.Web.ViewModel.LivroViewModel

@{
    ViewBag.Title = "Exclusão";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title"> @Html.DisplayFor(model => model.Titulo)</span>
                <div class="row">
                    <h4>Deseja realmente excluir o livro @Html.DisplayFor(model => model.Titulo)?</h4>
                </div>
                <div class="row">
                    <div class="col s12 m12 right-align">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn red" })
                                <input type="submit" value="Excluir" class="btn btn-default green" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Livro/Details.cshtml
@model LivrariaHBSIS.Web.ViewModel.LivroViewModel

@{
    ViewBag.Title = "Detalhes";
}
<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title"> @Html.DisplayFor(model => model.Titulo)</span>
                <div class="row">
                    <div class="col s12 m12 right-align">
                        @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn" })
                        @Html.ActionLink("Voltar", "Index", new object { }, new { @class = "btn" })
                    </div>
                </div>
                <div class="row">
                    <dl>
                        <dt>
                            <b>@Html.DisplayNameFor(model => model.Titulo):</b>
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Titulo)
                        </dd>

                        <dt>
                            <b>@Html.DisplayNameFor(model => model.Descricao):</b>
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Descricao)
                        </dd>

                        <dt>
                            <b>@Html.DisplayNameFor(model => model.GeneroSelecionado):</b>
                        </dt>

                        <dd>
                            @if (Model.GeneroLivro != null)
                            {
                                @Html.DisplayFor(model => model.GeneroLivro.Descricao)
                            }

                        </dd>

                        <dt>
                            <b> @Html.DisplayNameFor(model => model.AutorSelecionado):</b>
                        </dt>

                        <dd>
                            @if (Model.AutorPrincipal != null)
                            {
                                @Html.DisplayFor(model => model.AutorPrincipal.Nome)
                            }
                        </dd>

                        <dt>
                            <b>@Html.DisplayNameFor(model => model.EditoraSelecionada):</b>
                        </dt>

                        <dd>
                            @if (Model.EditoraPublicacao != null)
                            {
                                @Html.DisplayFor(model => model.EditoraPublicacao.Nome)
                            }
                        </dd>

                        <dt>
                            <b>@Html.DisplayNameFor(model => model.AnoPublicacao):</b>
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.AnoPublicacao)
                        </dd>

                        <dt>
                            <b>@Html.DisplayNameFor(model => model.Isbn):</b>
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Isbn)
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Livro/Edit.cshtml
@model LivrariaHBSIS.Web.ViewModel.LivroViewModel

@{
    ViewBag.Title = "Edição";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title">Editar Livro</span>
                <div class="row">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row">
                            <div class="input-field col s12">
                                @Html.LabelFor(model => model.Titulo)
                                @Html.EditorFor(model => model.Titulo, new { @class = "validate", @id = "titulo" })
                                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                @Html.LabelFor(model => model.Descricao)
                                @Html.TextAreaFor(model => model.Descricao, new { @class = "materialize-textarea validade", @id = "descricao", data_length = "400" })
                                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6">
                                @Html.LabelFor(model => model.AnoPublicacao)
                                @Html.TextBoxFor(model => model.AnoPublicacao, new { @type = "number", @min = "1452", @id = "anoPublicacao" })
                                @Html.ValidationMessageFor(model => model.AnoPublicacao, "", new { @class = "text-danger" })
                            </div>
                            <div class="input-field col s6">
                                @Html.LabelFor(model => model.Isbn)
                                @Html.TextBoxFor(model => model.Isbn, new { @type = "number", @id = "isbn" })
                                @Html.ValidationMessageFor(model => model.Isbn, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6 m6">
                                @Html.DropDownListFor(model => model.AutorSelecionado, (SelectList)ViewBag.SelectListAutores)
                                @Html.LabelFor(model => model.AutorSelecionado)
                            </div>
                            <div class="input-field col s6 m6">
                                @Html.DropDownListFor(model => model.GeneroSelecionado, (SelectList)ViewBag.SelectListGeneros)
                                @Html.LabelFor(model => model.GeneroSelecionado)
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6 m6">
                                @Html.DropDownListFor(model => model.EditoraSelecionada, (SelectList)ViewBag.SelectListEditoras)
                                @Html.LabelFor(model => model.EditoraSelecionada)
                            </div>
                        </div>

                        <div class="row">
                            <div class="col s12 right-align">
                                @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn red" })
                                <input type="submit" value="Salvar" class="btn btn-default" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(document).ready(function () {
        $('input#input_text, textarea#descricao').characterCounter();
    });
</script>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Livro/Index.cshtml
@model IEnumerable<LivrariaHBSIS.Web.ViewModel.LivroViewModel>

@{
    ViewBag.Title = "Livros";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title">Acervo de Livros</span>
                <div class="row">
                    <div class="col s12 m12 right-align">
                        @Html.ActionLink("Incluir Livro", "Create", "Livro", new object { }, new { @class = "btn" })
                    </div>
                </div>

                <table class="striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Titulo)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.AnoPublicacao)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Isbn)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Titulo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.AnoPublicacao)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Isbn)
                                </td>
                                <td>
                                    <a class="btn-floating light-green" href="@Url.Action("Edit", "Livro", new { id = item.Id })"><i class="material-icons">mode_edit</i></a>
                                    <a class="btn-floating light-blue" href="@Url.Action("Details", "Livro", new { id = item.Id })"><i class="material-icons">visibility</i></a>
                                    <a class="btn-floating red" href="@Url.Action("Delete", "Livro", new { id = item.Id })"><i class="material-icons">delete</i></a>
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>

            </div>
        </div>
    </div>
</div>