LivrariaHBSIS/LivrariaHBSIS.Web/Controllers/AutorController.cs
using LivrariaHBSIS.domain;
using LivrariaHBSIS.domain.Interfaces.Services;
using LivrariaHBSIS.Web.ViewModels;
using System.Linq;
using System.Web.Mvc;

namespace LivrariaHBSIS.Web.Controllers
{
    public class AutorController : Controller
    {
        private readonly IAutorService _autorService;
        public AutorController(IAutorService autorService)
        {
            _autorService = autorService;
        }

        public ActionResult Index()
        {
            var autoresViewModel = _autorService.ListarAutores()
                .Select(autor => new AutorViewModel(autor.Id, autor.Nome)
                )
                .ToList();
            return View(autoresViewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(AutorViewModel autorViewModel)
        {
            try
            {
                var autor = new Autor
                {
                    Id = autorViewModel.Id,
                    Nome = autorViewModel.Nome
                };

                _autorService.IncluirAutor(autor);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var autor = _autorService.RecuperarAutorPorId(id);
            return View(new AutorViewModel(autor.Id, autor.Nome));
        }

        [HttpPost]
        public ActionResult Edit(int id, AutorViewModel autorViewModel)
        {
            try
            {
                var autor = new Autor
                {
                    Id = autorViewModel.Id,
                    Nome = autorViewModel.Nome
                };

                _autorService.EditarAutor(autor);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            var autor = _autorService.RecuperarAutorPorId(id);
            return View(new AutorViewModel(autor.Id, autor.Nome));
        }

        [HttpPost]
        public ActionResult Delete(int id, AutorViewModel autorViewModel)
        {
            try
            {
                var autor = new Autor
                {
                    Id = autorViewModel.Id,
                    Nome = autorViewModel.Nome
                };

                _autorService.RemoverAutor(autor);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Autor/Create.cshtml
@model LivrariaHBSIS.Web.ViewModels.AutorViewModel

@{
    ViewBag.Title = "Inclusão";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title">Incluir autor</span>
                <div class="row">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="row">
                            <div class="input-field col s12">
                                @Html.LabelFor(model => model.Nome)
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "validate" } })
                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s12 right-align">
                                @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn red" })
                                <input type="submit" value="Salvar" class="btn btn-default" />
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Autor/Delete.cshtml
@model LivrariaHBSIS.Web.ViewModels.AutorViewModel

@{
    ViewBag.Title = "Exclusão";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title"> @Html.DisplayFor(model => model.Nome)</span>
                <div class="row">
                    <h4>Deseja realmente excluir o autor @Html.DisplayFor(model => model.Nome)?</h4>
                </div>
                <div class="row">
                    <div class="col s12 m12 right-align">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn red" })
                                <input type="submit" value="Excluir" class="btn btn-default green" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Autor/Edit.cshtml
@model LivrariaHBSIS.Web.ViewModels.AutorViewModel
@{
    ViewBag.Title = "Edição";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title">Editar Autor</span>
                <div class="row">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="row">
                            <div class="input-field col s12">
                                @Html.LabelFor(model => model.Nome)
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "validate" } })
                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s12 right-align">
                                @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn red" })
                                <input type="submit" value="Salvar" class="btn btn-default" />
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Autor/Index.cshtml
@model IEnumerable<LivrariaHBSIS.Web.ViewModels.AutorViewModel>

@{
    ViewBag.Title = "Autores";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title">Autores</span>
                <div class="row">
                    <div class="col s12 m12 right-align">
                        @Html.ActionLink("Incluir Autor", "Create", "Autor", new object { }, new { @class = "btn" })
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 m12">
                        <table class="striped">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Nome)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Nome)
                                        </td>
                                        <td>
                                            <a class="btn-floating light-green" href="@Url.Action("Edit", "Autor", new { id = item.Id })"><i class="material-icons">mode_edit</i></a>
                                            <a class="btn-floating red" href="@Url.Action("Delete", "Autor", new { id = item.Id })"><i class="material-icons">delete</i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>