LivrariaHBSIS/LivrariaHBSIS.Web/Controllers/EditoraController.cs
using LivrariaHBSIS.domain.Interfaces.Services;
using LivrariaHBSIS.Web.ViewModel;
using System.Linq;
using System.Web.Mvc;

namespace LivrariaHBSIS.Web.Controllers
{
    public class EditoraController : Controller
    {
        private IEditoraService _editoraService;

        public EditoraController(IEditoraService editoraService)
        {
            _editoraService = editoraService;
        }
        public ActionResult Index()
        {
            var editorasViewModel = _editoraService.ListarEditoras().Select(e => new EditoraViewModel { Id = e.Id, Nome = e.Nome }).ToList();
            return View(editorasViewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(EditoraViewModel editoraViewModel)
        {
            try
            {
                _editoraService.IncluirEditora(editoraViewModel.EditoraViewModelToEditora());
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(long id)
        {
            var editora = _editoraService.RecuperarEditoraPorId(id);
            return View(new EditoraViewModel { Id = editora.Id, Nome = editora.Nome });
        }

        [HttpPost]
        public ActionResult Edit(int id, EditoraViewModel editoraViewModel)
        {
            try
            {
                _editoraService.EditarEditora(editoraViewModel.EditoraViewModelToEditora());
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(long id)
        {
            var editora = _editoraService.RecuperarEditoraPorId(id);
            return View(new EditoraViewModel { Id = editora.Id, Nome = editora.Nome });
        }

        [HttpPost]
        public ActionResult Delete(int id, EditoraViewModel editoraViewModel)
        {
            try
            {
                _editoraService.RemoverEditora(editoraViewModel.EditoraViewModelToEditora());
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Editora/Create.cshtml
@model LivrariaHBSIS.Web.ViewModel.EditoraViewModel

@{
    ViewBag.Title = "Inclusão";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title">Incluir Editora</span>
                <div class="row">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="row">
                            <div class="input-field col s12">
                                @Html.LabelFor(model => model.Nome)
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "validate" } })
                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s12 right-align">
                                @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn red" })
                                <input type="submit" value="Salvar" class="btn btn-default" />
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Editora/Delete.cshtml
@model LivrariaHBSIS.Web.ViewModel.EditoraViewModel

@{
    ViewBag.Title = "Exclusão";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title"> @Html.DisplayFor(model => model.Nome)</span>
                <div class="row">
                    <h4>Deseja realmente excluir a editora @Html.DisplayFor(model => model.Nome)?</h4>
                </div>
                <div class="row">
                    <div class="col s12 m12 right-align">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn red" })
                                <input type="submit" value="Excluir" class="btn btn-default green" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Editora/Edit.cshtml
@model LivrariaHBSIS.Web.ViewModel.EditoraViewModel

@{
    ViewBag.Title = "Edição";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title">Editar Editora</span>
                <div class="row">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="row">
                            <div class="input-field col s12">
                                @Html.LabelFor(model => model.Nome)
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "validate" } })
                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s12 right-align">
                                @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn red" })
                                <input type="submit" value="Salvar" class="btn btn-default" />
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

LivrariaHBSIS/LivrariaHBSIS.Web/Views/Editora/Index.cshtml
@model IEnumerable<LivrariaHBSIS.Web.ViewModel.EditoraViewModel>

@{
    ViewBag.Title = "Editoras";
}

<div class="row">
    <div class="col s12 m12">
        <div class="card animated fadeInRight">
            <div class="card-content">
                <span class="card-title">Editora</span>
                <div class="row">
                    <div class="col s12 m12 right-align">
                        @Html.ActionLink("Incluir Editoras", "Create", "Editora", new object { }, new { @class = "btn" })
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 m12">
                        <table class="striped">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Nome)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Nome)
                                        </td>
                                        <td>
                                            <a class="btn-floating light-green" href="@Url.Action("Edit", "Editora", new { id = item.Id })"><i class="material-icons">mode_edit</i></a>
                                            <a class="btn-floating red" href="@Url.Action("Delete", "Editora", new { id = item.Id })"><i class="material-icons">delete</i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>